### ISSUE TITLE
Pull first draft of wiki

### ISSUE THREAD

**Issue by hiclef** [codeforboston/safe-water#75]
I have created a first draft of the clean-water wiki on [my fork of the repo](http://github.com/h-clef/safe-water.wiki). Francois need to manually pull these files to to the main page.

**Comment by de-la-viz** [comment]
page not found!

**Comment by hiclef** [comment]
Sorry. [try this](http://github.com/h-clef/safe-water/wiki).

**Comment by de-la-viz** [comment]
Currently have an issue while trying to follow [this](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github):

_git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository._

_Please make sure you have the correct access rights
and the repository exists._

==> will do some research and try something else.

**Comment by de-la-viz** [comment]
Tried following [this](http://roman-ivanov.blogspot.com/2013/11/how-to-merge-github-wiki-changes-from.html), but still error:

(venv_base) MacBook-Pro:safe-water dla$ git clone https://github.com/codeforboston/safe-water.wiki.git
_Cloning into 'safe-water.wiki'...
remote: Enumerating objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 3
Unpacking objects: 100% (3/3), done._  

(venv_base) MacBook-Pro:safe-water dla$ cd safe-water.wiki/  

(venv_base) MacBook-Pro:safe-water.wiki dla$ git fetch https://github.com/h-clef/safe-water.wiki.git master:master-hclef
_warning: no common commits
remote: Enumerating objects: 41, done.
remote: Total 41 (delta 0), reused 0 (delta 0), pack-reused 41
Unpacking objects: 100% (41/41), done.
From https://github.com/h-clef/safe-water.wiki_
 _* [new branch]      master     -> master-hclef_   

(venv_base) MacBook-Pro:safe-water.wiki dla$ git checkout master-hclef
_Switched to branch 'master-hclef'_  

(venv_base) MacBook-Pro:safe-water.wiki dla$ git reset --hard ac4d410b64dea2d47e031130fde499bb9f38d01a
_fatal: Could not parse object 'ac4d410b64dea2d47e031130fde499bb9f38d01a'._

... Not sure how to resolve this. Considering just copy-pasting, as suggested by Tom ;)

**Comment by de-la-viz** [comment]
@h-clef: I finished coying the wiki. Thanks a lot for your updates! We still need to discuss with the tech helpers at CfB to see if we can improve our workflow.
