### ISSUE TITLE
UX Research for Data Viz & Comms

### ISSUE THREAD

**Issue by jdseags** [codeforboston/safe-water#77]
User Experience Research for CRWA Data Visualization project. Includes interviews & surveys to understand existing and potential users of CRWA website water sample data.  

Link to working research proposal & interview guide document: https://docs.google.com/document/d/1b1ul-941FnWESAw9Cqgslo2I4DmrVlq4XVXSw_YwYyI/edit#heading=h.g0cgv9ydnjr1

Workstream team members: Josie-Dee Seagren, Chris LaRue, Emi Gaal

**Comment by de-la-viz** [comment]
CRWA User Research Readout Phase 1: https://docs.google.com/presentation/d/1Uz4YF2_vrfo1kajW6JntpupbPtHUQBaUAq_JM178JvQ
