### ISSUE TITLE
Database columns are unclean

### ISSUE THREAD

**Issue by nicholasjin** [codeforboston/safe-water#93]
A number of columns are malformatted, or have multiple labels that correspond to missingness, etc.

**Comment by de-la-viz** [comment]
Done! 
Pull request: https://github.com/codeforboston/safe-water/pull/96
Notebook where the cleaning is commented: https://github.com/codeforboston/safe-water/blob/master/projects/crwa/notebooks/njin-data-cleaning.ipynb
Cleaned Data (output of previous notebook) as .csv: https://github.com/codeforboston/safe-water/blob/master/projects/crwa/data/charles_river_samples_interim/results_merged_cleaned.csv
